### ISSUE TITLE
require error

### ISSUE THREAD

**Issue by litt1e-p** [chenxch/unplugin-vue-setup-extend-plus#1]
usage:
```js
plugins: [
  // require('unplugin-vue-setup-extend-plus/webpack') // no work
  require('unplugin-vue-setup-extend-plus/webpack').default({}) // error occured
]
```
error msg:
```js
<i> [webpack-dev-server] 404s will fallback to '/index.html'
  building [==                  ] 10% (2.5 s)MY_WORKSPACE\unplugin-vue-setup-extend-plus\dist\webpack.js:56
    const filename = FILENAME_RE.exec(id)[1];
                                         ^

TypeError: Cannot read properties of null (reading '1')
    at Object.supportScriptName (MY_WORKSPACE\unplugin-vue-setup-extend-plus\dist\webpack.js:56:42)
    at Object.transform (MY_WORKSPACE\unplugin-vue-setup-extend-plus\dist\webpack.js:75:30)
    at Object.transform (MY_WORKSPACE\unplugin\dist\webpack\loaders\transform.js:67:38)
    at LOADER_EXECUTION (MY_WORKSPACE\loader-runner\lib\LoaderRunner.js:132:14)
    at runSyncOrAsync (MY_WORKSPACE\loader-runner\lib\LoaderRunner.js:133:4)
    at iterateNormalLoaders (MY_WORKSPACE\loader-runner\lib\LoaderRunner.js:251:2)
    at MY_WORKSPACE\loader-runner\lib\LoaderRunner.js:224:4
    at MY_WORKSPACE\webpack\lib\NormalModule.js:834:15
    at Array.eval (eval at create (MY_WORKSPACE\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (MY_WORKSPACE\enhanced-resolve\lib\CachedInputFileSystem.js:27:15)
```

**Comment by chenxch** [comment]
Can you provide a simple demo?

**Comment by chenxch** [comment]
@litt1e-p 
Sorry to keep you waiting, you can upgrade to version 0.2.1 and the problem has been fixed.

**Comment by chenxch** [comment]
@litt1e-p 
Welcome to version 0.2.4, which fixes the issue with cjs exports.
e.g.
```js
// require('unplugin-vue-setup-extend-plus/webpack').default({ /* options */ })
require('unplugin-vue-setup-extend-plus/webpack')({ /* options */ })
```

**Comment by litt1e-p** [comment]
still same error occured

**Comment by chenxch** [comment]
> still same error occured

Can you provide a simple demo?

**Comment by chenxch** [comment]
@litt1e-p I have used webpack5 to build the project several times, and the plugin can be installed. If there are no other problems, I will close the problem.

**Comment by litt1e-p** [comment]
will you give me a demo for test with my other plugin together?

**Comment by chenxch** [comment]
> will you give me a demo for test with my other plugin together?

I will submit the demo and let you know in the evening.

**Comment by litt1e-p** [comment]
thanks

**Comment by chenxch** [comment]
> thanks

Sry,I used `vue-cli` before.

I relocated the `webpack` issue and fixed some other issues. These problems are caused by `webpack`  `id` path slashes as opposed to `vite` and all the other differences.

You can upgrade to version `0.2.5`, the demo is in `playground-webpack`.

![image](https://user-images.githubusercontent.com/23251408/174137600-033b8373-1c30-4626-b638-ac4c25382503.png)

**Comment by litt1e-p** [comment]
yeah, it works now, thanks a lot

**Comment by chenxch** [comment]
> yeah, it works now, thanks a lot

Ok, thank you very much for your feedback and use, have a good day.
