### ISSUE TITLE
0.4.1找不到类型声明

### ISSUE THREAD

**Issue by trague** [chenxch/unplugin-vue-setup-extend-plus#10]
`npm create vue@3`创建的项目，只添加了`unplugin-vue-setup-extend-plus`，其它未做修改

![image](https://user-images.githubusercontent.com/24466492/207246082-266dc682-17fc-4b7f-9b11-2e5f5d18c9cf.png)

**Comment by chenxch** [comment]
提供一个demo？

**Comment by trague** [comment]
[https://github.com/trague/unplugin-vue-setup-extend-plus-demo](https://github.com/trague/unplugin-vue-setup-extend-plus-demo)

**Comment by chenxch** [comment]
升级到0.4.4
