### ISSUE TITLE
Cannot find module 'dist\vite.cjs'

### ISSUE THREAD

**Issue by trague** [chenxch/unplugin-vue-setup-extend-plus#11]
demo: [https://github.com/trague/unplugin-vue-setup-extend-plus-demo](https://github.com/trague/unplugin-vue-setup-extend-plus-demo)

![image](https://user-images.githubusercontent.com/24466492/207477054-4e0eafe8-c356-4419-b379-40d22bee1593.png)

![image](https://user-images.githubusercontent.com/24466492/207476803-4b9da920-1a08-4792-b7d2-e57b2e4f1853.png)

**Comment by trague** [comment]
0.4.4版本

**Comment by chenxch** [comment]
sry，我的测试demo是module  type，修复版本0.4.5已发布

**Comment by trague** [comment]
感谢。

**Comment by chenxch** [comment]
> 感谢。

辛苦你帮忙测试了💗
