### ISSUE TITLE
出现语法错误，本地devServer会中断。去除插件后仅出现报错内容，本地服务正常运行。

### ISSUE THREAD

**Issue by wenjie79** [chenxch/unplugin-vue-setup-extend-plus#12]
![image](https://user-images.githubusercontent.com/38197250/212579165-de13eab5-e485-4257-8f83-fdc425ee4a0c.png)

**Comment by chenxch** [comment]
方便提供一个demo么

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/212669215-cfdd9711-8bb0-4f0e-9ba9-3924a260dabb.png)
这个错误是说你写了中文的封号吧

**Comment by wenjie79** [comment]
> 
就是出现类似于中文分号的语法错误后，vue编译报错，本地服务器直接就挂了。正常的报错信息应该是这样（去掉插件后的效果），麻烦大佬帮忙看看
![image](https://user-images.githubusercontent.com/38197250/212785726-52915f6f-fe01-4dc7-a1fb-212c4b38f2af.png)

**Comment by chenxch** [comment]
> > 
> 
> 就是出现类似于中文分号的语法错误后，vue编译报错，本地服务器直接就挂了。正常的报错信息应该是这样（去掉插件后的效果），麻烦大佬帮忙看看 ![image](https://user-images.githubusercontent.com/38197250/212785726-52915f6f-fe01-4dc7-a1fb-212c4b38f2af.png)

我明白你的意思了，就是平时这种报错只是会提示，修改过来了就能正常继续开发了，但是现在加入了插件dev进程就直接崩溃了是吧，我会在近期进行排查修复。

**Comment by chenxch** [comment]
@wenjie79 0.4.6 修复版本已经发布了哈
