### ISSUE TITLE
v0.4版本不生效

### ISSUE THREAD

**Issue by wenjie79** [chenxch/unplugin-vue-setup-extend-plus#13]
不好意思，又碰到一个问题，烦请指教下。

**我原本是0.3.2版本正常，升级到0.4.*后(尝试了0.4.5和0.4.6版本)没有生成name，截图是demo跑起来的结果。**

**0.3.2版本结果**
![image](https://user-images.githubusercontent.com/38197250/216007135-ec06b6fa-5a53-43c4-bc25-21db1cceb094.png)

**0.4.6版本demo示例结果**
![image](https://user-images.githubusercontent.com/38197250/216004195-15732830-201d-4874-913e-18c8573824f3.png)

**Comment by chenxch** [comment]
收到，今晚我排查下

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/216366776-14a172c3-8c03-4409-abbd-c69ff88ae17e.png)
@wenjie79 十分感谢反馈， 0.4.7版本已修复。

**Comment by chenxch** [comment]
@wenjie79 建议升级到0.4.8

**Comment by wenjie79** [comment]
> @wenjie79 建议升级到0.4.8
![image](https://user-images.githubusercontent.com/38197250/217171953-7c80ec03-fc79-4051-912c-b21515c470ad.png)
 webpack示例中还是没生成name呢，麻烦再帮忙看下

**Comment by chenxch** [comment]
@wenjie79  收到

**Comment by chenxch** [comment]
@wenjie79 0.4.9已修复，定位到是transformInclude上游修改的原因

**Comment by wenjie79** [comment]
> 
可以正常生成了，感谢帮助
