### ISSUE TITLE
feat: 默认值支持

### ISSUE THREAD

**Issue by object-kaz** [chenxch/unplugin-vue-setup-extend-plus#4]
script setup 中的 name 属性支持根据 插件选项，设置默认值。

增加的一些插件选项：
+  'defaultName: "none" | "fileName" | "relativeName" | (id: string) => ({name: string} | { policy: string })'
    + none: 如果用户未填写，则不自动设置名称
    + fileName: 如果用户未设置name属性，则使用文件名（去掉后缀并转驼峰）作为组件名。如 `NavBar.vue` => NavBar
    + relativeName: 如果用户未设置name属性，则使用相对路径（去掉后缀和'/'，并转驼峰）作为组件名。如 `user/Login.vue` => UserLogin
    + 自定义函数: 可以让用户根据id设置合适的策略，或者直接根据id设置组件名称

由于用户可能会script标签定义组件的name属性，这跟本插件设置的默认name起冲突。因此需要在script setup 增加一个开关属性 'no-default-name'，如果用户手动设置了这个属性，则插件不作 defaultName 的处理。

**Comment by chenxch** [comment]
0.3.0版本已经发布， 参数名称进行了调整，[详见](https://github.com/chenxch/unplugin-vue-setup-extend-plus#readme)

**Comment by chenxch** [comment]
在处理fileName的时候从测试中来看和默认行为一样，目前代码中还是包含了这部分的处理。

**Comment by object-kaz** [comment]
> 在处理fileName的时候从测试中来看和默认行为一样，目前代码中还是包含了这部分的处理。

vue的插件在编译的时候给组件加上了 `__name` 属性，和插件里面的 fileName 在行为上确实差不多，要不试着把 fileName 取消吧

**Comment by chenxch** [comment]
> vue的插件在编译的时候给组件加上了 `__name` 属性，和插件里面的 fileName 在行为上确实差不多，要不试着把 fileName 取消吧

好

**Comment by chenxch** [comment]
0.3.2版本已经发布
