### ISSUE TITLE
Add polyfill for replaceAll 

### ISSUE THREAD

**Issue by litt1e-p** [chenxch/unplugin-vue-setup-extend-plus#5]
`replaceAll` function needs polyfill in old node versions which will raising error for it

**Comment by chenxch** [comment]
Ok, i'll replace `replaceAll` with regex.

**Comment by litt1e-p** [comment]
you can use babel to polyfill it

**Comment by chenxch** [comment]
OK, I'll look at it later.

**Comment by chenxch** [comment]
version 0.3.1.
Sorry, only the regular way is used for now.
