### ISSUE TITLE
webpack 构建生产组件名称会丢失

### ISSUE THREAD

**Issue by latte03** [chenxch/unplugin-vue-setup-extend-plus#7]
vue2.7 webpack 构建生产组件名称会丢失
生成环境：
![image](https://user-images.githubusercontent.com/33367218/184800166-9cc89ccc-987c-4923-870d-4449cc451424.png)

开发环境：
![image](https://user-images.githubusercontent.com/33367218/184800226-f4a859b6-f64f-4889-a4a5-747cbb1a2345.png)

**Comment by chenxch** [comment]
感谢反馈，近期会进行问题排查。

**Comment by chenxch** [comment]
我这边进行测试是没问题的，方便提供下一个简易的demo么

**Comment by latte03** [comment]
> 我这边进行测试是没问题的，方便提供下一个简易的demo么

[vue2-setup-mf](https://github.com/agan-agan/vue2-setup-mf) 可以试一下这个仓库里的，有用模块联邦，remote 库以production的模式运行，在host上就vue组件就没有name属性了，不知道是不是模块联邦哪里影响到了。

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/188913957-40beec31-8735-42b1-a0f0-e91a4eee36a4.png)
我试着在remote项目中使用了下组件后host项目那边的也生效了
