### ISSUE TITLE
In some cases, names are not available

### ISSUE THREAD

**Issue by Loveyless** [chenxch/unplugin-vue-setup-extend-plus#8]
When I write a component ,i use jsx/tsx , as right as rain.

![image](https://user-images.githubusercontent.com/88988179/199049673-df39b866-8719-4a76-8388-fcc8f5b0188e.png)

Write the name

When I write a component ,i use <script setup>
![image](https://user-images.githubusercontent.com/88988179/199049445-6af94e55-ee7e-421b-9c3d-beebc3b0ef0e.png)
If I don't write it a new <script> and defineComponent({ name: 'SFCButtonSetup' }) , while the use of ```<script lang="ts" setup name="SFCButtonSetup" inheritAttrs="false">``` To be such a 👇

![image](https://user-images.githubusercontent.com/88988179/199051148-7ed6e007-69b3-4a0d-9e2e-ee93b044af0b.png)

and when Manually fill out👇
![image](https://user-images.githubusercontent.com/88988179/199051367-b0231f09-7afb-4030-900c-5081d3fa4a4d.png)
And everything is fine

**Comment by Loveyless** [comment]
https://github.com/Loveyless/less-ui/commit/49e4a4c2ebb2410bd05a457bfc48097fff026875

**Comment by chenxch** [comment]
Received, I will reply you in detail later.

**Comment by chenxch** [comment]
Need to add content in `script setup`.
e.g
```vue
<script lang="ts" setup name="SFCButtonSetup" inheritAttrs="false">
import { ref } from 'vue'
const a = ref(0)
</script>

<template>
  <button>
    SFCSetup
    <slot />
  </button>
</template>
```

output:
![image](https://user-images.githubusercontent.com/23251408/199230497-79b4837c-2009-4599-886a-5f28ffed2590.png)

**Comment by Loveyless** [comment]
It's amazing that suddenly it's okay because it wasn't before.
thank you very much.

**Comment by chenxch** [comment]
Okey,  i will close this issue, have a good day.

**Comment by Loveyless** [comment]
感谢 福州的好兄弟 哈哈哈
