### ISSUE TITLE
unmet peer vite@^2.3.0

### ISSUE THREAD

**Issue by trague** [chenxch/unplugin-vue-setup-extend-plus#9]
使用vite3.x版本，提示unmet peer vite@^2.3.0: found 3.2.4， 能否更新unplugin版本？unplugin已发布1.0.0

![image](https://user-images.githubusercontent.com/24466492/206953243-c8b746f1-5973-4f5d-b93f-76489ab283b4.png)

**Comment by chenxch** [comment]
感谢提醒，马上安排

**Comment by chenxch** [comment]
可以升级到0.4.0版本了

**Comment by trague** [comment]
感谢。

**Comment by chenxch** [comment]
> 感谢。

0.4.1版本哈， 0.4.0版本文档错误重新发了
